import sharp from 'sharp';
/** Verify generated bytes actually decode before reporting a successful image tool. */
export async function assertDecodableImage(dataUrl, signal) {
  signal?.throwIfAborted();
  if (typeof dataUrl !== 'string' || dataUrl.length > 6*1024*1024 || !/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/]+=*$/.test(dataUrl)) throw new Error('生成图片格式无效');
  const bytes = Buffer.from(dataUrl.slice(dataUrl.indexOf(',')+1), 'base64');
  const decoder = sharp(bytes, {limitInputPixels:16_000_000, failOn:'warning'});
  const cancel = () => decoder.destroy(new Error('图片校验已取消'));
  signal?.addEventListener('abort',cancel,{once:true});
  try {
    await decoder.resize({width:4,height:4,fit:'inside'}).raw().toBuffer();
    signal?.throwIfAborted();
  } catch (error) {
    if (signal?.aborted) signal.throwIfAborted();
    throw new Error('图片服务返回的图片无法解码或尺寸过大');
  } finally { signal?.removeEventListener('abort',cancel); decoder.destroy(); }
}
