import test from 'node:test';
import assert from 'node:assert/strict';
import { createScene } from '../apps/web/src/studio/model.ts';
import { validateTemplateDefinition, instantiateTemplate, discoverTemplateVariables, variableValue, TEMPLATE_LIMITS } from '../packages/schema/templates.ts';
const imageA='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6dN4AAAAASUVORK5CYII=';
const imageB='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
function fixture(){const scene=createScene('weekend');scene.id='source';scene.messages=[{id:'photo',participantId:scene.participants[1].id,type:'image',text:'',time:'18:30',asset:imageA},{id:'line',participantId:scene.selfId,type:'text',text:'See you soon.',time:'18:31'}];return {name:'Meetup',scene,variables:[{key:'name',label:'Person',type:'text',target:{entity:'participant',id:scene.participants[1].id,field:'name'}},{key:'avatar',label:'Avatar',type:'image',target:{entity:'participant',id:scene.participants[1].id,field:'avatar'}},{key:'photo',label:'Photo',type:'image',target:{entity:'message',id:'photo',field:'asset'}},{key:'reply',label:'Reply',type:'text',target:{entity:'message',id:'line',field:'text'}}]};}

test('template instances have independent names, photos and IDs without mutating the source',()=>{const source=fixture(),before=JSON.stringify(source);const a=instantiateTemplate(source,{name:'Ava',avatar:imageA,photo:imageA,reply:'By the window.'},'instance-a');const b=instantiateTemplate(source,{name:'Noah',avatar:imageB,photo:imageB,reply:'At the entrance.'},'instance-b');assert.equal(a.ok,true);assert.equal(b.ok,true);assert.equal(a.value.participants[1].name,'Ava');assert.equal(b.value.participants[1].name,'Noah');assert.notEqual(a.value.messages[0].asset,b.value.messages[0].asset);assert.notEqual(a.value.id,b.value.id);a.value.messages[0].text='edited';assert.equal(b.value.messages[0].text,'');assert.equal(JSON.stringify(source),before);});
test('omitted values keep snapshot defaults, while unknown and hostile keys fail atomically',()=>{const source=fixture();assert.equal(instantiateTemplate(source,{},'copy').ok,true);assert.equal(instantiateTemplate(source,{unlisted:'oops'},'copy').ok,false);assert.equal(instantiateTemplate(source,JSON.parse('{"__proto__":{"polluted":true}}'),'copy').ok,false);assert.equal(instantiateTemplate(source,{name:'Fine',photo:'https://example.org/photo.png'},'copy').ok,false);assert.equal({}.polluted,undefined);assert.equal(source.scene.messages[0].asset,imageA);});
test('variable declarations require existing compatible unique targets and bounded labels',()=>{for(const transform of [v=>({...v,key:'constructor'}),v=>({...v,key:'../../bad'}),v=>({...v,label:'x'.repeat(81)}),v=>({...v,type:'image'}),v=>({...v,target:{entity:'participant',id:'missing',field:'name'}}),v=>({...v,target:{entity:'scene',field:'__proto__'}})]){const raw=fixture();raw.variables=[transform(raw.variables[0])];assert.equal(validateTemplateDefinition(raw).ok,false);}const raw=fixture();raw.variables.push({...raw.variables[0],key:'alias'});assert.equal(validateTemplateDefinition(raw).ok,false);});
test('replacement type, image bounds and fresh ID are enforced',()=>{for(const values of [{name:42},{name:''},{name:'x'.repeat(101)},{reply:'x'.repeat(4001)},{photo:'data:image/svg+xml;base64,PHN2Zy8+'},{photo:'data:image/png;base64,'+'a'.repeat(TEMPLATE_LIMITS.imageChars)}])assert.equal(instantiateTemplate(fixture(),values,'copy').ok,false);assert.equal(instantiateTemplate(fixture(),{},'source').ok,false);assert.equal(instantiateTemplate(fixture(),{},'../copy').ok,false);});
test('discovery produces reusable typed variables without interpreting user text as code',()=>{const raw=fixture();raw.scene.messages[1].text='${constructor} <script>alert(1)</script>';const vars=discoverTemplateVariables(raw.scene);assert.ok(vars.some(v=>v.type==='image'&&v.target.entity==='message'));const template={...raw,variables:vars};const result=validateTemplateDefinition(template);assert.equal(result.ok,true);const textVar=vars.find(v=>v.target.entity==='message'&&v.target.field==='text');assert.equal(variableValue(raw.scene,textVar),raw.scene.messages[1].text);assert.equal(instantiateTemplate(template,{},'next').value.messages[1].text,raw.scene.messages[1].text);});
test('snapshot normalization is detached and rejects unsupported template fields',()=>{const raw=fixture();const result=validateTemplateDefinition(raw);assert.equal(result.ok,true);result.value.scene.participants[0].name='Changed';assert.notEqual(raw.scene.participants[0].name,'Changed');assert.equal(validateTemplateDefinition({...raw,html:'<script/>'}).ok,false);assert.equal(validateTemplateDefinition({...raw,schemaVersion:2}).ok,false);});

test('reference templates replace explicit regions without changing shared image assets',()=>{
 const raw=fixture();raw.scene.reference={source:imageA,assets:[{id:'shared',dataUrl:imageA,description:'Source image'}],plan:{schemaVersion:1,im:'wechat',surface:'ios',width:600,height:900,warnings:[],edits:[{id:'first',kind:'image',assetId:'shared',box:[100,100,200,200],background:'#ffffff',color:'#000000'},{id:'second',kind:'image',assetId:'shared',box:[500,100,200,200],background:'#ffffff',color:'#000000'},{id:'words',kind:'text',text:'Original',box:[100,400,600,100],fontSize:16,background:'#ffffff',color:'#000000'}]}};
 raw.variables=[{key:'portrait',label:'Portrait',type:'image',target:{entity:'reference',id:'first',field:'image'}},{key:'words',label:'Words',type:'text',target:{entity:'reference',id:'words',field:'text'}}];
 const before=JSON.stringify(raw),result=instantiateTemplate(raw,{portrait:imageB,words:'Replaced'},'reference-copy');
 assert.equal(result.ok,true);const doc=result.value.reference;
 assert.notEqual(doc.plan.edits[0].assetId,doc.plan.edits[1].assetId);
 assert.equal(doc.assets.find(a=>a.id===doc.plan.edits[0].assetId).dataUrl,imageB);
 assert.equal(doc.assets.find(a=>a.id===doc.plan.edits[1].assetId).dataUrl,imageA);
 assert.equal(doc.plan.edits[2].text,'Replaced');assert.equal(doc.source,imageA);assert.equal(JSON.stringify(raw),before);
});
