import { useState } from 'react';
import { useCopy } from '../i18n';
import { validateScene, type Scene } from '../studio/model';
export default function ReferenceInspector({scene,selected,locked,onChange,onSelect}:{scene:Scene;selected:string;locked:boolean;onChange:(s:Scene)=>void;onSelect:(id:string)=>void}) {
 const copy = useCopy().reference;
 const [error,setError]=useState('');const r=scene.reference!;const edit=r.plan.edits.find(e=>`@patch:${e.id}`===selected);
 function patch(p:Record<string,unknown>){const next={...scene,reference:{...r,plan:{...r.plan,edits:r.plan.edits.map(e=>e===edit?{...e,...p}:e)}}};const v=validateScene(next);if(v.ok&&v.scene){setError('');onChange(v.scene);}else setError(v.errors.join('；'));}
 return <details className="agent-manual agent-inspector" open><summary>{copy.title}</summary><fieldset disabled={locked}><label>{copy.selected}<select value={selected} onChange={e=>onSelect(e.target.value)}><option value="">{copy.all}</option>{r.plan.edits.map(e=><option key={e.id} value={`@patch:${e.id}`}>{e.text||e.assetId||e.id}</option>)}</select></label>{edit&&<>{edit.kind==='text'?<label>{copy.text}<textarea value={edit.text} onChange={e=>patch({text:e.target.value})}/></label>:<label>{copy.image}<select value={edit.assetId} onChange={e=>patch({assetId:e.target.value})}>{r.assets.map(a=><option key={a.id} value={a.id}>{a.description||a.id}</option>)}</select></label>}<div className="inspector-pair">{copy.axes.map((label,i)=><label key={i}>{label}（0–1000）<input type="number" step="0.1" value={edit.box[i]} onChange={e=>patch({box:edit.box.map((n,k)=>k===i?Number(e.target.value):n)})}/></label>)}</div>{edit.kind==='text'&&<><label>{copy.font}<input type="number" min={10} max={160} value={edit.fontSize} onChange={e=>patch({fontSize:Number(e.target.value)})}/></label><label>{copy.color}<input type="color" value={edit.color} onChange={e=>patch({color:e.target.value})}/></label><label>{copy.background}<input type="color" value={edit.background} onChange={e=>patch({background:e.target.value})}/></label></>}<button className="agent-button" onClick={()=>{onChange({...scene,reference:{...r,plan:{...r.plan,edits:r.plan.edits.filter(e=>e!==edit)}}});onSelect('');}}>{copy.remove}</button></>}</fieldset>{error&&<p role="alert">{error}</p>}</details>;
}
